name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O workflow será executado quando houver push na branch 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Faça o checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instale o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Certifique-se de usar a mesma versão do seu ambiente local

      # 3. Instale dependências e gere o build
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 4. Deploy para a branch gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Pasta gerada pelo build
